// bb-plugin-aim — an AOL Instant Messenger-style desktop for bb-app.
//
// Compiled by `bb plugin build` into dist/app.js + dist/app.css. React and
// @get-bb/plugin-sdk/app are provided by the BB app at load time (never
// bundled), so this file must be loaded by BB, not imported directly.
//
// There is exactly ONE AIM surface: the desktop page, reached from its own
// sidebar entry. It is registered as a `navPanel` (which gets a sidebar item
// and a host-wrapped panel route) and renders the classic-Windows desktop,
// the buddy list, and the floating IM windows. The former always-on
// `experimental_appOverlay` registration is intentionally removed so the AIM
// chrome only exists on this page.
import { definePluginApp } from "@get-bb/plugin-sdk/app";
import { DesktopPage } from "./aim/DesktopPage";
// 98.css (Windows 98 OS base), regenerated by scripts/make-98-scoped.mjs and
// scoped under .aim-xp so it cannot leak into the host app. Imported BEFORE
// aim.css so the AIM chrome/palette layer can override wherever the desktop
// needs to differ. 98.css is the era-correct OS base for a 1999 AIM desktop
// (XP.css "Luna" is Windows XP / 2001).
import "./aim/WIN98_scoped.css";
import "./aim.css";

export default definePluginApp((app) => {
  app.slots.navPanel({
    id: "aim-desktop",
    title: "AIM",
    icon: "Monitor",
    // Routed at /plugins/aim/aim-desktop; the component receives the
    // remainder as `subPath` (always "" here).
    path: "desktop",
    component: DesktopPage,
  });
});